### ISSUE TITLE
Django Oscar successively used in production in a Motorcycle trials e-commerce website

### ISSUE THREAD

**Issue by webinventdotcom** [django-oscar/oscarcommerce.com#1]
Hi,

I just wanted to tell you that Django Oscar 1.5 is used in a small french e-commerce website that mainly sells Motorcycle trials stuff. It uses a redirect to a secured bank procedure for the payments.

https://www.garage-champion-millau-trial.fr

I really like this framework !
If you want you can put this website in the cases study page.  :-)

http://oscarcommerce.com/cases.html

Geoffroy

**Comment by sasha0** [comment]
Thanks for the feedback Geoffroy!

We'll add it to the case studies.
