### ISSUE TITLE
django oscar used in production for a small swiss publishing house

### ISSUE THREAD

**Issue by yvess** [django-oscar/oscarcommerce.com#2]
Hi

We ([taywa](https://www.taywa.ch)) build the site https://www.hierundjetzt.ch/ with oscar 1.6 and django-cms.
It uses saferpay as payment gateway. The products are auto-updated from a custom ERP system.

You can add it to the cases study page, if you want. 
http://oscarcommerce.com/cases.html

thanks
Yves

**Comment by specialunderwear** [comment]
Hi I've just added it, thanks!
